package com.jxqixin.trafic.constant;
/**
 * 人员档案类别
 */
public enum  EmpArchiveType {
    RESUME,CONTRACT,QUALIFICATIONDOCUMENT,JOBHISTORY,INDUCTIONTRAINING,SAFETYRESPONSIBILITYAGREEMENT,TRAININGEXAMINE,OTHERDOCUMENT
}
